#配置druid数据源
spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/test_liuyi?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
      username: root
      password: 123456
      # 配置初始化大小、最小、最大
      initial-size: 5
      min-idle: 10
      max-active: 20
      # 配置获取连接等待超时的时间
      max-wait: 60000
      #      pool-prepared-statements:
      #      max-pool-prepared-statement-per-connection-size:
      #      max-open-prepared-statements: #和上面的等价
      # 验证是否连接成功sql
      validation-query: select 1
      validation-query-timeout: 10000
      #      test-on-borrow: false
      #      test-on-return: false
      #      test-while-idle:
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 2000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 600000
      max-evictable-idle-time-millis: 900000

#配置mybatis-plus
mybatis-plus:
  mapper-locations: classpath:mapper/*/*.xml
